More scripts and organizing

diff --git a/bin/checksum b/bin/checksum
--- a/bin/checksum
+++ b/bin/checksum
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+crc32c=""
+md5=""
+output=""
+lines=""
 SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
 # echo "SCRIPT_DIR: ${SCRIPT_DIR}"
 # echo "BASH_SOURCE[0]: ${BASH_SOURCE[0]}"
@@ -39,14 +43,8 @@ spinner() {
 	printf "    \r"
 }
 
-# Init...
-crc32c=""
-md5=""
-output=""
-lines=""
-
 # (re:IMGNX)...bash.
-echo -e "${B}${D}${ROSE}${BKGD_CYBERPUNK}(${B}${WHITE}r${BKGD_CYBERPUNK}${B}${WHITE}e${R}${AMBER}${B}:${R}${PEACH}I${ROSE}M${DEEP_MAGENTA}G${D}${ILLICIT_PURPLE}N${EGGPLANT}X${MIDNIGHT_EXPRESS})${D}...${R}${B}${WHITE}${BKGD_BLACK} bash.${R}"
+echo -e "${B}${D}${I}${ROSE}${BKGD_CYBERPUNK}(${B}${WHITE}r${BKGD_CYBERPUNK}${B}${WHITE}e${R}${AMBER}${B}:${R}${PEACH}I${ROSE}M${DEEP_MAGENTA}G${D}${ILLICIT_PURPLE}N${EGGPLANT}X${MIDNIGHT_EXPRESS})${D}   ${R}${B}${WHITE}${BKGD_BLACK} bash.${R}"
 # https://cloud.google.com/storage/docs/resumable-uploads#integrity_checks
 
 if [ $# -eq 0 ]; then
@@ -57,20 +55,45 @@ else
 	input=$1
 fi
 
-. normalize_path.sh
+paths="$(normalize_path -q $input)"
 
-$full_path = $imgnx_normalized_path_full_path
-$object_path = $imgnx_normalized_path_object_path
+# echo -e "Paths: $paths"
+if [[ $paths =~ \" ]]; then
+	# echo "Path has a space in it."
+	if [[ $paths =~ ^\"(.*)\"[[:space:]]\"(.*)\"$ ]]; then
+		full_path="${BASH_REMATCH[1]}"
+		object_path="${BASH_REMATCH[2]}"
+	fi
+else
+	# echo "Path does not have a space in it."
+	if [[ $paths =~ (.*)[[:space:]](.*) ]]; then
+		full_path="${BASH_REMATCH[1]}"
+		object_path="${BASH_REMATCH[2]}"
+	fi
+fi
 
-echo "Path: $full_path"
+if [[ "$full_path" == "" || "$object_path" == "" ]]; then
+	if [[ $input =~ (\\$)(\/$)(\.{0}) ]]; then
+		echo -e "${MAGENTA} ::pensive:: ${MAGENTA}${DEEP_RED}Read Error: Could not find directory $input${R}"
+	else
+		echo -e "${MAGENTA} ::pensive:: ${MAGENTA}${DEEP_RED}Read Error: Could not find file $input${R}"
+	fi
+	exit 1
+fi
+
+# echo "Full (normalized) path: $full_path"
+# echo "Object path: $object_path"
 
 # Check...
-echo -e "${R}${B}(R)emote${D}:....${R}${PACMAN}gs://imgfunnels.com$object_path${R}"
-echo -e "${R}${B}(L)ocal${D}:.....${R}${B}${MS_PACMAN_KISS_PINK}$full_path${R}"
-echo -e "Is this correct?    "
-echo -en "${D}Press Enter to continue:"
+echo -e "${D}First, we need the ${R}path...${R}"
+echo -e "${D}Does this look right?${R}"
+echo
+echo -e "${R}${B}Loc${D}al:     ${R}${B}${PACMAN}$full_path${R}"
+echo -e "${R}${B}Rem${D}ote:    ${MS_PACMAN_KISS_PINK}gs://imgfunnels.com${N}${B}$object_path${R}"
+echo
+echo -en "${D}Press [Enter] to confirm:${R}"
 read -p ""
-echo -e "Checking integrity of ${R}$input..."
+echo -e "${D}Checking integrity of ${R}$input..."
 echo -e "${D}Generating Crc/Md5 chec${CYAN}k${UFO_GREEN}s${CHARTREUSE}u${AMBER}m${ORANGE}.${RED}.${DEEP_RED}.${R}"
 
 # Mapping...
@@ -188,10 +211,10 @@ echo -e "Processing complete."
 		echo -e "${BKGD_BLACK}${MIDNIGHT_EXPRESS}${B}Decoded: ${R}${BKGD_BLACK}$crc32c_decoded${R}"
 		echo -e "${BKGD_BLACK}${PEARL}${B}Md5 Checksum/Hash:${R}${BKGD_BLACK}${UFO_GREEN}    $md5_hash${R}"
 		echo -e "${BKGD_BLACK}${MIDNIGHT_EXPRESS}${B}Decoded: ${R}${BKGD_BLACK}$md5_decoded${R}"
-		echo -e "${BKGD_BLACK}${PURPLE}${B}🛸 🎸 Match! 🍄 👽${R}"
+		echo -e "${BKGD_BLACK}${PURPLE}${B}🍄 It's a match! 💩${R}"
 		exit 0
 	else
-		echo -e "${DEEP_RED}🤔 Integrity check failed! 💩${R}"
+		echo -e "${MAGENTA} ::thinking:: ${DEEP_RED} Integrity check failed!${R}"
 		if [[ "$crc32c_hash" == "" ]]; then
 			echo -e "${DEEP_RED}Crc32c hash not found!${R}"
 			echo -e "${WHITE}Crc32c Checksum: $crc32c_checksum${R}"
